CC=gcc
CC_FLAGS_COMMON=-Wall
CC_FLAGS_DEBUG=-g
CC_FLAGS_RELEASE=

FLEX=flex
BISON=bison

BUILD_DEBUG_FOLDER=build-debug
LIBMUJ7_TARGET_DEBUG=$(BUILD_DEBUG_FOLDER)/libmuj7.so 
MAIN_TARGET_DEBUG=$(BUILD_DEBUG_FOLDER)/main.o

SRC_FOLDER=src
SRC_MUJ7_FOLDER=$(SRC_FOLDER)/cpu
LIBMUJ7_SOURCE=$(SRC_MUJ7_FOLDER)/muj7cpu.c
MAIN_SOURCE=$(SRC_MUJ7_FOLDER)/main.c

SRC_MUJ7_HELPER_FOLDER=$(SRC_FOLDER)/helper
MUJ7_HELPER_SOURCE=$(SRC_MUJ7_HELPER_FOLDER)/muj7helper.c

SRC_ASSEMBLER_FOLDER=$(SRC_FOLDER)/assembler
ASSEMBLER_LEX_SOURCE=$(SRC_ASSEMBLER_FOLDER)/muj7asm.l
ASSEMBLER_YACC_SOURCE=$(SRC_ASSEMBLER_FOLDER)/muj7asm.y
ASSEMBLER_LEX_TARGET=$(BUILD_DEBUG_FOLDER)/lex.yy.c
ASSEMBLER_YACC_TARGET=$(BUILD_DEBUG_FOLDER)/y.tab.c
ASSEMBLER_TARGET=$(BUILD_DEBUG_FOLDER)/muj7asm.o

SRC_DEBUGGER_FOLDER=$(SRC_FOLDER)/debugger
SRC_DEBUGGER_SOURCE=$(SRC_DEBUGGER_FOLDER)/muj7debugger.c
DEBUGGER_TARGET=$(BUILD_DEBUG_FOLDER)/muj7debugger.o

TEST_FOLDER=test
TEST_SOURCE=$(TEST_FOLDER)/cputest.c
TEST_TARGET=$(TEST_FOLDER)/cputest.o

.PHONY: clean

all: debug assembler debugger

debug: $(MAIN_TARGET_DEBUG) 

$(LIBMUJ7_TARGET_DEBUG): $(LIBMUJ7_SOURCE) 
	mkdir -p $(BUILD_DEBUG_FOLDER)
	$(CC) $(CC_FLAGS_COMMON) $(CC_FLAGS_DEBUG) -shared $(LIBMUJ7_SOURCE) -o $(LIBMUJ7_TARGET_DEBUG) 

$(MAIN_TARGET_DEBUG): $(MAIN_SOURCE) $(LIBMUJ7_TARGET_DEBUG)
	$(CC) $(CC_FLAGS_COMMON) $(CC_FLAGS_DEBUG) $(MAIN_SOURCE) -L$(BUILD_DEBUG_FOLDER) -lmuj7 -o $(MAIN_TARGET_DEBUG) 

tests: $(TEST_TARGET)
	LD_LIBRARY_PATH=$(BUILD_DEBUG_FOLDER) $(TEST_TARGET)	

$(TEST_TARGET): $(TEST_SOURCE) 
	$(CC) -I$(SRC_FOLDER) -L$(BUILD_DEBUG_FOLDER) $(TEST_SOURCE) -lcunit -lmuj7 -o $(TEST_TARGET)

assembler: $(ASSEMBLER_TARGET)

$(ASSEMBLER_TARGET): $(ASSEMBLER_LEX_TARGET) $(ASSEMBLER_YACC_TARGET)
	$(CC) -o $(ASSEMBLER_TARGET) $(ASSEMBLER_LEX_TARGET) $(ASSEMBLER_YACC_TARGET) -lfl

$(ASSEMBLER_LEX_TARGET): $(ASSEMBLER_LEX_SOURCE) 
	mkdir -p $(BUILD_DEBUG_FOLDER)
	$(FLEX) -o $(ASSEMBLER_LEX_TARGET) $(ASSEMBLER_LEX_SOURCE)

$(ASSEMBLER_YACC_TARGET): $(ASSEMBLER_YACC_SOURCE) 
	$(BISON) -o $(ASSEMBLER_YACC_TARGET) -dy $(ASSEMBLER_YACC_SOURCE)

debugger: $(DEBUGGER_TARGET)

$(DEBUGGER_TARGET): $(SRC_DEBUGGER_SOURCE) $(MUJ7_HELPER_SOURCE)
	$(CC) $(SRC_DEBUGGER_SOURCE) $(MUJ7_HELPER_SOURCE) -L$(BUILD_DEBUG_FOLDER) -lmuj7 -lncurses $(CC_FLAGS_DEBUG) -o $(DEBUGGER_TARGET)

clean:
	rm -Rf $(BUILD_DEBUG_FOLDER)
